name: Tests

on:
  push:
    branches: ["main", "work"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run viewer tests
        working-directory: viewer
        run: npm test

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Build viewer dataset
        run: |
          python scripts/build_viewer_data.py \
            external-data/SBLGNT/data/sblgnt/text/Mark.txt \
            viewer/data/mark.json \
            --display-name "Gospel of Mark" \
            --book-id mark

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload viewer artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: viewer

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
